//))))sai.net##/
=pod

=head1 L<LaTeXML|http://dlmf.nist.gov/LaTeXML/>

=for html <a href="https://github.com/brucemiller/LaTeXML/actions?query=workflow%3ALinux"><img src="https://github.com/brucemiller/LaTeXML/workflows/Linux/badge.svg"></a>
  <a href="https://github.com/brucemiller/LaTeXML/actions?query=workflow%3AWindows"><img src="https://github.com/brucemiller/LaTeXML/workflows/Windows/badge.svg"></a>
  <a href="https://raw.githubusercontent.com/brucemiller/LaTeXML/master/LICENSE"><img src="http://img.shields.io/badge/license-CC0-blue.svg" alt="license" data-canonical-src="http://img.shields.io/badge/license-CC0-blue.svg" style="max-width:100%;"></a>
  <a href="https://metacpan.org/release/LaTeXML"><img src="https://badge.fury.io/pl/LaTeXML.svg" alt="CPAN version" height="18"></a>

LaTeXML is a TeX & LaTeX to XML, HTML, MathML, ePub, JATS, ... converter.

See the included L<Manual|http://dlmf.nist.gov/LaTeXML/manual.pdf> for documentation.

The official project home page is at L<http://dlmf.nist.gov/LaTeXML/>.

LaTeXML development is currently hosted on L<GitHub|https://github.com/brucemiller/LaTeXML>,
where you can retrieve and browse the current source,
along with an L<Issue tracker|https://github.com/brucemiller/LaTeXML/issues>
and L<Wiki|https://github.com/brucemiller/LaTeXML/wiki>.

For general discussion feel free to join the L<mailing list|http://lists.informatik.uni-erlangen.de/mailman/listinfo/latexml>.


=head1 L<LICENSE|http://dlmf.nist.gov/LaTeXML/notices.html>

See the L<LICENSE|https://github.com/brucemiller/LaTeXML/blob/master/LICENSE> file
for copyright and licensing information.

=head1 L<AUTHOR|https://www.nist.gov/people/bruce-r-miller>

Bruce R. Miller, L<mailto:bruce.miller@nist.gov>,
Deyan Ginev, L<mailto:deyan.ginev@gmail.com>.

=cut
