=pod

=head1 L<LaTeXML|http://dlmf.nist.gov/LaTeXML/>

LaTeXML is a TeX and LaTeX to XML/HTML/MathML converter.
From XML it can generate various flavors of HTML,
MathML and ePub, with other formats under development.
See the included manual.pdf for an documentation.

The home page is at L<http://dlmf.nist.gov/LaTeXML/>.
LaTeXML development is currently hosted at
L<https://github.com/brucemiller/LaTeXML>,
where you can retrieve and browse the current source,
along with an Issue tracker
L<https://github.com/brucemiller/LaTeXML/issues>
and Wiki L<https://github.com/brucemiller/LaTeXML/wiki>.
A mailing list for discussion is hosted at
L<http://lists.jacobs-university.de/mailman/listinfo/project-latexml>

=head1 STATUS

See L<LaTeXML|http://dlmf.nist.gov/LaTeXML/> for current releases.

=for html Build status: <a href="https://travis-ci.org/brucemiller/LaTeXML"><img src="https://travis-ci.org/brucemiller/LaTeXML.svg?branch=master"></a>

=head1 LICENSE

See the F<LICENSE> file for copyright and licensing information.

=head1 AUTHOR

L<mailto:bruce.miller@nist.gov>

=cut
