#!/usr/bin/env perl
# /=====================================================================\ #
# |  bibtexmlr                                                          | #
# | Run compiled .bst code                                              | #
# |=====================================================================| #
# | Part of LaTeXML                                                     | #
# |---------------------------------------------------------------------| #
# | Tom Wiesing <tom.wiesing@gmail.com>                                 | #
# \=====================================================================/ #

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../lib";

use LaTeXML::Post::BiBTeX::Cmd::bibtexmlr;
my $exitcode = LaTeXML::Post::BiBTeX::Cmd::bibtexmlr->main(@ARGV);
exit $exitcode;

1;
