#!/usr/bin/env perl
# /=====================================================================\ #
# |  bibtexmlc                                                          | #
# | BiBTeXML .bst compiler entry point                                  | #
# |=====================================================================| #
# | Part of LaTeXML                                                     | #
# |---------------------------------------------------------------------| #
# | Tom Wiesing <tom.wiesing@gmail.com>                                 | #
# \=====================================================================/ #

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../lib";

use LaTeXML::Post::BiBTeX::Cmd::bibtexmlc;
my $exitcode = LaTeXML::Post::BiBTeX::Cmd::bibtexmlc->main(@ARGV);
exit $exitcode;

1;
