#!/usr/bin/env perl
# /=====================================================================\ #
# |  makebbl                                                            | #
# | Tool script to quickly generate the output of BibTeX                | #
# |=====================================================================| #
# | Part of LaTeXML                                                     | #
# |---------------------------------------------------------------------| #
# | Tom Wiesing <tom.wiesing@gmail.com>                                 | #
# \=====================================================================/ #

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../lib";

use LaTeXML::Post::BiBTeX::Cmd::makebbl;
my $exitcode = LaTeXML::Post::BiBTeX::Cmd::makebbl->main(@ARGV);
exit $exitcode;

1;
